if(!firebase.apps.length) firebase.initializeApp(window.KOVELI_FIREBASE_CONFIG);
const body=document.getElementById("usersBody"), editor=document.getElementById("editor"), msg=document.getElementById("msg"); let selected=null;
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function show(t,type="ok"){msg.textContent=t;msg.className="msg show "+type;}
function dateText(v){return v?new Date(v).toLocaleString():"—";}
firebase.auth().onAuthStateChanged(async user=>{if(!user){location.href="login.html";return;} const a=window.getKoveliApprovedUser(user); if(!a||String(a.role).toLowerCase()!=="admin"){location.href="home.html";return;} load();});
async function load(){try{const s=await firebase.database().ref("registrations").once("value"), rows=[];s.forEach(c=>rows.push(c.val()));rows.sort((a,b)=>(b.requestedAt||0)-(a.requestedAt||0));document.getElementById("pendingCount").textContent=rows.filter(x=>x.status!=="approved").length;document.getElementById("approvedCount").textContent=(window.KOVELI_USERS||[]).filter(x=>x.active!==false).length;body.innerHTML=rows.length?rows.map((u,i)=>`<tr><td>${esc(u.name)}</td><td><b>${esc(u.username||"—")}</b></td><td>${esc(u.email)}</td><td>${esc(u.status||"pending")}</td><td>${esc(dateText(u.requestedAt))}</td><td><button class="table-btn" data-i="${i}">Open</button></td></tr>`).join(""):`<tr><td colspan="6" class="empty">No registrations found.</td></tr>`;body.querySelectorAll("button[data-i]").forEach(b=>b.onclick=()=>openUser(rows[+b.dataset.i]));}catch(e){show(e.message,"error");}}
function openUser(u){selected=u;editor.classList.remove("hidden");document.getElementById("editName").value=u.name||"";document.getElementById("editUsername").value=u.username||"";document.getElementById("editEmail").value=u.email||"";document.getElementById("generated").value="";editor.scrollIntoView({behavior:"smooth"});}
function entry(){if(!selected)return "";const o={uid:selected.uid,username:document.getElementById("editUsername").value.trim().toLowerCase(),email:document.getElementById("editEmail").value.trim(),name:document.getElementById("editName").value.trim(),role:document.getElementById("editRole").value,department:document.getElementById("editDepartment").value.trim(),landingPage:document.getElementById("editLanding").value.trim()||"home.html",active:true};return JSON.stringify(o,null,4);}
document.getElementById("generateBtn").onclick=()=>document.getElementById("generated").value=entry();document.getElementById("copyBtn").onclick=async()=>{const t=document.getElementById("generated").value||entry();document.getElementById("generated").value=t;await navigator.clipboard.writeText(t);show("User entry copied. Paste it into script/user.js.");};document.getElementById("markBtn").onclick=async()=>{if(!selected)return;await firebase.database().ref("registrations/"+selected.uid).update({status:"approved",approvedAt:firebase.database.ServerValue.TIMESTAMP});show("Registration marked approved. Make sure the user entry is deployed in script/user.js.");load();};document.getElementById("refreshBtn").onclick=load;document.getElementById("logout").onclick=async()=>{await firebase.auth().signOut();location.href="login.html";};
